### ISSUE TITLE
help wanted: multi boot.oat in /system/framework

### ISSUE THREAD

**Issue by kmahyyg** [liudongmiao/Brevent#30]
I used the lineage os 14.1
RedMi 3 (ido)
Android 7.1

I found two boot files.
/system/framework/arm/boot.oat
/system/framework/arm64/boot.oat
(Non-Odex Optimize Version, services.jar 2.29M)
My phone is in ARM-v8a (aarch64)
Which one should be patched?

**Comment by etnperlong** [comment]
I think you should patch arm64/boot.oat.My device is Redmi Note 3 MTK and it also has two boot.oat.I patch the one in folder arm64 and replace by Magisk.It works well!
            On 01/10/2017 18:30, kmahyyg wrote:I used the lineage os 14.1
RedMi 3 (ido)
Android 7.1
I found two boot files.
/system/framework/arm/boot.oat
/system/framework/arm64/boot.oat
(Non-Odex Optimize Version, services.jar 2.29M)
My phone is in ARM-v8a (aarch64)
Which one should be patched?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liudongmiao/Brevent","title":"liudongmiao/Brevent","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liudongmiao/Brevent"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"help wanted: multi boot.oat in /system/framework (#30)"}],"action":{"name":"View Issue","url":"https://github.com/liudongmiao/Brevent/issues/30"}}}

**Comment by etnperlong** [comment]
Oh sorry I haven't seen that your ROM is deodexed.May be you should try to patch services.jar directly.
            On 01/10/2017 18:30, kmahyyg wrote:I used the lineage os 14.1
RedMi 3 (ido)
Android 7.1
I found two boot files.
/system/framework/arm/boot.oat
/system/framework/arm64/boot.oat
(Non-Odex Optimize Version, services.jar 2.29M)
My phone is in ARM-v8a (aarch64)
Which one should be patched?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liudongmiao/Brevent","title":"liudongmiao/Brevent","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liudongmiao/Brevent"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"help wanted: multi boot.oat in /system/framework (#30)"}],"action":{"name":"View Issue","url":"https://github.com/liudongmiao/Brevent/issues/30"}}}

**Comment by aviraxp** [comment]
Both are fine I think.

**Comment by kmahyyg** [comment]
@etnperlong I'll try both from now on.But Only Crack ARM64 can still make an effect of ARMV7 app?

BTW, I ensure that there's no odex file in my device, all were *.dex or *.art.

**Comment by kmahyyg** [comment]
Got a solution.
Because of NON-ODEX version,i don't need boot.oat for patching.😂
