### ISSUE TITLE
无法通过 adb 启动黑域

### ISSUE THREAD

**Issue by leelings** [liudongmiao/Brevent#343]
尝试几次了都是这样
--- crash start ---
>>> logcat -b crash -t '03-30 23:32:51.000' -d
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-30 23:32:51.000' -d -s BreventLoader BreventServer
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
03-30 23:32:54.168 14596 14596 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-30 23:32:54.168 14596 14596 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-30 23:32:54.175 14596 14596 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
03-30 23:32:54.194 14596 14596 I BreventServer: Brevent Server 0.9.4 started
03-30 23:32:54.205 14596 14596 W BreventServer: Can't find ActivityManager.RECENT_INGORE_DOCKED_STACK_TOP_TASK
03-30 23:32:54.205 14596 14596 W BreventServer: Can't find ActivityManager.RECENT_INGORE_PINNED_STACK_TASKS
03-30 23:32:54.229 14596 14596 I BreventServer: brevent user: 0, uid: 2000
03-30 23:32:54.232 14596 14596 I BreventServer: brevent data directory: /data/user/0/com.android.shell
03-30 23:32:54.406 14596 14596 I BreventServer: loading brevent list
03-30 23:32:54.409 14596 14596 I BreventServer: loading brevent conf
03-30 23:32:55.009 14581 14581 E BreventLoader: worker 14596 exited on signal 9
--- brevent end ---

**Comment by liudongmiao** [comment]
对于低版本，没有 crash 日志，需要提供更多日志。

大约是 adb logcat -t '03-30 23:32:51.000' -d

就是每次出现以后，根据提示的时间，去掉 -b main，特别要注意里面的 Exception.

如果不会的话，找个时间，我远程上去吧。

**Comment by Flammulinavelutipes** [comment]
shamu:/ $ su
shamu:/ # /data/app/me.piebridge.brevent-1/lib/arm/libbrevent.so
checking............cannot listen port
please report bug to https://github.com/liudongmiao/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '03-31 14:52:11.000' -d
03-31 14:52:14.331  8348  8348 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
03-31 14:52:14.331  8348  8348 E AndroidRuntime: java.lang.reflect.InvocationTargetException
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1344)
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
03-31 14:52:14.331  8348  8348 E AndroidRuntime: Caused by: me.piebridge.brevent.server.d$a: Can't dump activities
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at me.piebridge.brevent.server.d.d(HideApi.java:311)
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.o(BreventServer.java:1179)
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:430)
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1325)
03-31 14:52:14.331  8348  8348 E AndroidRuntime:        ... 4 more
03-31 14:52:14.333  8348  8348 E AndroidRuntime: Error reporting crash
03-31 14:52:14.333  8348  8348 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-31 14:52:14.333  8348  8348 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
03-31 14:52:14.333  8348  8348 E AndroidRuntime:        at android.os.BinderProxy.transact(Binder.java:615)
03-31 14:52:14.333  8348  8348 E AndroidRuntime:        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
03-31 14:52:14.333  8348  8348 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
03-31 14:52:14.333  8348  8348 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-31 14:52:14.333  8348  8348 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '03-31 14:52:11.000' -d -s BreventLoader BreventServer
03-31 14:52:12.884  8337  8337 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
03-31 14:52:14.144  8348  8348 I BreventServer: classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.piebridge.brevent-1/base.apk"],nativeLibraryDirectories=[/system/lib, /vendor/lib, /system/lib, /vendor/lib]]]
03-31 14:52:14.144  8348  8348 I BreventServer: Brevent Server 0.9.4 started
03-31 14:52:14.159  8348  8348 I BreventServer: brevent user: 0, uid: 0
03-31 14:52:14.160  8348  8348 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
03-31 14:52:14.255  8348  8348 I BreventServer: loading brevent list03-31 14:52:14.256  8348  8348 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 36
03-31 14:52:14.256  8348  8348 I BreventServer: loading brevent conf03-31 14:52:14.261  8348  8348 D BreventServer: Can't dump widgets (ignore)
03-31 14:52:14.324  8348  8348 D BreventServer: check and brevent
03-31 14:52:14.325  8348  8348 D BreventServer: Can't dump notifications
03-31 14:52:14.328  8348  8348 D BreventServer: Can't dump widgets (ignore)
03-31 14:52:14.330  8348  8348 E BreventServer: Can't dump activities
03-31 14:52:14.330  8348  8348 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
03-31 14:52:14.330  8348  8348 E BreventServer:         at android.os.BinderProxy.transactNative(Native Method)
03-31 14:52:14.330  8348  8348 E BreventServer:         at android.os.BinderProxy.transact(Binder.java:615)
03-31 14:52:14.330  8348  8348 E BreventServer:         at android.os.BinderProxy.dump(Binder.java:631)
03-31 14:52:14.330  8348  8348 E BreventServer:         at me.piebridge.brevent.server.d.d(HideApi.java:305)
03-31 14:52:14.330  8348  8348 E BreventServer:         at me.piebridge.brevent.server.BreventServer.o(BreventServer.java:1179)
03-31 14:52:14.330  8348  8348 E BreventServer:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:430)
03-31 14:52:14.330  8348  8348 E BreventServer:         at me.piebridge.brevent.server.BreventServer.startBreventServer(BreventServer.java:1325)
03-31 14:52:14.330  8348  8348 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
03-31 14:52:14.330  8348  8348 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:1344)
03-31 14:52:14.330  8348  8348 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-31 14:52:14.330  8348  8348 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
03-31 14:52:14.349  8337  8337 E BreventLoader: worker 8348 exited on signal 9
03-31 14:52:14.349  8337  8337 D BreventLoader: signal arrived, update: 0
03-31 14:52:14.350  8336  8336 D BreventLoader: worker 8337 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/liudongmiao/Brevent/issues with log above

**Comment by liudongmiao** [comment]
> 03-31 14:52:14.330 8348 8348 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died

重启手机吧。
