### ISSUE TITLE
Can not listen port，没有网络权限

### ISSUE THREAD

**Issue by windong** [liudongmiao/Brevent#50]
checking.............
cannot listen port, please report bug
--- crash info start ---
02-17 08:32:30.460 10408 10420 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: Thread-1
02-17 08:32:30.460 10408 10420 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at me.piebridge.brevent.loader.Brevent.run(Brevent.java:60)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: ... 1 more
02-17 08:32:30.460 10408 10420 E AndroidRuntime: Caused by: java.net.SocketException: Permission denied
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at java.net.ServerSocket.bind(ServerSocket.java:377)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:802)
02-17 08:32:30.460 10408 10420 E AndroidRuntime: ... 3 more
02-17 08:32:30.489 10408 10420 E AndroidRuntime: Error reporting crash
02-17 08:32:30.489 10408 10420 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
02-17 08:32:30.489 10408 10420 E AndroidRuntime: at android.os.BinderProxy.transactNative(Native Method)
02-17 08:32:30.489 10408 10420 E AndroidRuntime: at android.os.BinderProxy.transact(Binder.java:615)
02-17 08:32:30.489 10408 10420 E AndroidRuntime: at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5163)
02-17 08:32:30.489 10408 10420 E AndroidRuntime: at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
02-17 08:32:30.489 10408 10420 E AndroidRuntime: at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-17 08:32:30.489 10408 10420 E AndroidRuntime: at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
--- crash info end ---
--- main info start ---
02-17 08:32:29.949 10408 10420 D BreventServer: brevent data directory: /data/user_de/0/com.android.shell
02-17 08:32:30.431 10408 10420 I BreventServer: power_screen_state, tag: 2728, event: 7
02-17 08:32:30.432 10408 10420 I BreventServer: notification_cancel_all, tag: 2752, event: 6
02-17 08:32:30.437 10408 10420 I BreventServer: am_new_intent, tag: 30003, event: 2
02-17 08:32:30.439 10408 10420 I BreventServer: am_pause_activity, tag: 30013, event: 3
02-17 08:32:30.439 10408 10420 I BreventServer: am_proc_start, tag: 30014, event: 4
02-17 08:32:30.442 10408 10420 I BreventServer: am_switch_user, tag: 30041, event: 5
02-17 08:32:30.443 10408 10420 I BreventServer: am_focused_activity, tag: 30043, event: 1
02-17 08:32:30.459 10408 10420 D BreventLoader: Can't run brevent server
02-17 08:32:30.459 10408 10420 D BreventLoader: java.lang.reflect.InvocationTargetException
02-17 08:32:30.459 10408 10420 D BreventLoader: at java.lang.reflect.Method.invoke(Native Method)
02-17 08:32:30.459 10408 10420 D BreventLoader: at me.piebridge.brevent.loader.Brevent.run(Brevent.java:57)
02-17 08:32:30.459 10408 10420 D BreventLoader: at java.lang.Thread.run(Thread.java:761)
02-17 08:32:30.459 10408 10420 D BreventLoader: Caused by: java.net.SocketException: Permission denied
02-17 08:32:30.459 10408 10420 D BreventLoader: at java.net.ServerSocket.createImpl(ServerSocket.java:309)
02-17 08:32:30.459 10408 10420 D BreventLoader: at java.net.ServerSocket.getImpl(ServerSocket.java:258)
02-17 08:32:30.459 10408 10420 D BreventLoader: at java.net.ServerSocket.bind(ServerSocket.java:377)
02-17 08:32:30.459 10408 10420 D BreventLoader: at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-17 08:32:30.459 10408 10420 D BreventLoader: at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:802)
02-17 08:32:30.459 10408 10420 D BreventLoader: ... 3 more
02-17 08:32:30.460 10408 10408 D BreventLoader: Brevent Server quit in 60 seconds, quit
--- main info end ---
3|OnePlus2:/ #

**Comment by liudongmiao** [comment]
> 02-17 08:32:30.460 10408 10420 E AndroidRuntime: Caused by: java.net.SocketException: Permission denied

请帮忙进入  adb shell 之后，看下能不能访问网络，不过内置也没有什么可以访问网络的工具啊。

我后期看下这种问题用户数，决定是否要支持。因为如果不监听网络的话，有两个不好：

- 黑域没法知道到底有没有成功
- 在更新黑域清单，修改设置的时候，处理起来相对费劲些

**Comment by windong** [comment]
可以ping通外部网址，算吗？

**Comment by liudongmiao** [comment]
ping 不使用 shell 的网络权限，每个程序都可以调用。

你可以下载个 busybox，执行下 busybox wget 之类，如 busybox wget http://piebridge.me/robots.txt

**Comment by windong** [comment]
OnePlus2:/ # busybox wget http://piebridge.me/robots.txt
Connecting to piebridge.me (206.253.164.174:80)
wget: can't open 'robots.txt': Read-only file system

**Comment by dudukee** [comment]
Unable to open log device 'crash'
checking...reset_reason_init
..........
cannot listen port, please report bug
--- crash info start ---
Unable to open log device 'crash'
--- crash info end ---
--- main info start ---
02-17 10:51:55.062  1749  1765 D BreventServer: brevent data directory: /data/us
er/0/com.android.shell
02-17 10:51:55.382  1749  1765 D BreventLoader: Can't run brevent server
02-17 10:51:55.382  1749  1765 D BreventLoader: java.lang.reflect.InvocationTarg
etException
02-17 10:51:55.382  1749  1765 D BreventLoader:         at java.lang.reflect.Met
hod.invoke(Native Method)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at me.piebridge.brevent.
loader.Brevent.run(Brevent.java:57)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at java.lang.Thread.run(
Thread.java:818)
02-17 10:51:55.382  1749  1765 D BreventLoader: Caused by: java.lang.NumberForma
tException: Invalid int: ""
02-17 10:51:55.382  1749  1765 D BreventLoader:         at java.lang.Integer.inv
alidInt(Integer.java:138)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at java.lang.Integer.par
seInt(Integer.java:358)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at java.lang.Integer.par
seInt(Integer.java:334)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at ku.g(HideApi.java:388
)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at ku.d(HideApi.java:355
)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at ku.a(HideApi.java:268
)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.k(BreventServer.java:674)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.a(BreventServer.java:662)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.<init>(BreventServer.java:128)
02-17 10:51:55.382  1749  1765 D BreventLoader:         at me.piebridge.brevent.
server.BreventServer.main(BreventServer.java:796)
02-17 10:51:55.382  1749  1765 D BreventLoader:         ... 3 more
02-17 10:51:55.382  1749  1749 D BreventLoader: Brevent Server quit in 60 second
s, quit
--- main info end ---

大佬,这是什么情况?
@liudongmiao

**Comment by liudongmiao** [comment]
@dudukee 你下个最新的版本，看下。然后重新开个 issue

**Comment by liudongmiao** [comment]
10 天内没继续反馈，关闭。
